# Generated by Django 2.2.4 on 2019-08-21 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('sent', models.BooleanField(default=False)),
                ('rsvp_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('plus_ones', models.IntegerField(default=0)),
                ('rsvp', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Party')),
            ],
        ),
    ]
