# Generated by Django 2.2.4 on 2019-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190821_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
